source:
  java_class: org.gt.connections.google.StorageReader
  config:
    bucket: gerard-my-bucket
    blob_name: source.json
    converter: org.gt.conversions.read.FromJsonConverter
target:
  java_class: org.gt.connections.jdbc.JdbcWriter
  config:
    batch_size: 1000
    commit_size: 1000
    jdbc_url: jdbc:mysql://localhost:3306/airflow?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Amsterdam&rewriteBatchedStatements=true
    sql: >
      INSERT INTO stations ( station_id, name, status, latitude, longitude, location )
      VALUES (?, ?, ?, ?, ?, ?)
transforms:
  - java_class: org.gt.transforms.JavascriptTransformer
    config:
      script: >
        var ObjectArrayType = Java.type("java.lang.Object[]");

        var transform = function(row) {
          var xformed = new ObjectArrayType(6);
          var node = row[0];

          xformed[0] = node.get("station_id").asText();
          xformed[1] = node.get("name").asText();
          xformed[2] = node.get("status").asText();
          xformed[3] = node.get("latitude").asDouble();
          xformed[4] = node.get("longitude").asDouble();
          xformed[5] = node.get("location").asText();

          return xformed;
        };
