source:
  java_class: org.gt.connections.jdbc.JdbcReader
  reader:
    fetch_size: 1000
  config:
    jdbc_url: jdbc:postgresql://localhost:5432/dvdrentals
    sql: >
      SELECT rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update
      FROM public.rental
target:
  java_class: org.gt.connections.jdbc.JdbcWriter
  writer:
    batch_size: 1000
    commit_size: 1000
  config:
    jdbc_url: jdbc:mysql://localhost:3306/airflow?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Amsterdam&rewriteBatchedStatements=true
    sql: >
      INSERT INTO rental ( rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update )
      VALUES (?, ?, ?, ?, ?, ?, ?)

#sourceConversion:
#targetConversion:
#transformations:
#  user:
